## Notebook for testing

In [1]:
import pandas as pd
import numpy as np

In [45]:
actors_df = pd.read_csv("../data/imdb_ijs_actors.tsv.gz", sep="\t")
roles_df = pd.read_csv("../data/imdb_ijs_roles.tsv.gz", sep="\t")

### EDA

In [46]:
actors_df.head()

   id first_name           last_name gender
0   2    Michael  'babeepower' Viera      M
1   3       Eloy         'Chincheta'      M
2   4   Dieguito         'El Cigala'      M
3   5    Antonio    'El de Chipiona'      M
4   6       José        'El Francés'      M

In [47]:
roles_df.head()

   actor_id  movie_id              role
0         2    280088            Stevie
1         2    396232  Various/lyricist
2         3    376687          Gitano 1
3         4    336265         El Cigala
4         5    135644           Himself

In [9]:
actors_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 817718 entries, 0 to 817717
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          817718 non-null  int64
 1   first_name  817718 non-null  object
 2   last_name   817717 non-null  object
 3   gender      817718 non-null  object
dtypes: int64(1), object(3)
memory usage: 25.0+ MB

In [10]:
roles_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3431966 entries, 0 to 3431965
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   actor_id  int64
 1   movie_id  int64
 2   role      object
dtypes: int64(2), object(1)
memory usage: 78.6+ MB

### Suppression des ID pairs

In [14]:
actors_pair_df = actors_df[actors_df.id % 2 == 0]

In [15]:
actors_pair_df.head()

   id first_name               last_name gender
0   2    Michael      'babeepower' Viera      M
2   4   Dieguito             'El Cigala'      M
4   6       José            'El Francés'      M
6   8    Marcial            'El Jalisco'      M
8  10  Francisco  'El Niño de la Manola'      M

### Jointure des 2 tables

In [27]:
df_merge = pd.merge(actors_pair_df, roles_df, left_on='id', right_on='actor_id', how='inner')

In [25]:
df_merge.head()

,id,first_name,last_name,gender,actor_id,movie_id,role
0,2,Michael,'babeepower' Viera,M,2,280088,Stevie
1,2,Michael,'babeepower' Viera,M,2,396232,Various/lyricist
2,4,Dieguito,'El Cigala',M,4,336265,El Cigala
3,6,José,'El Francés',M,6,12083,NaN
4,8,Marcial,'El Jalisco',M,8,101866,NaN

In [28]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1709640 entries, 0 to 1709639
Data columns (total 7 columns):
 #   Column      Dtype
---  ------      -----
 0   id          int64
 1   first_name  object
 2   last_name   object
 3   gender      object
 4   actor_id    int64
 5   movie_id    int64
 6   role        object
dtypes: int64(3), object(4)
memory usage: 91.3+ MB

### Count top 100 actor

In [43]:
df_count = (
        df_merge
        .groupby(['id', 'first_name', 'last_name'], as_index=False)
        .size()
        .rename(columns={'size': 'role_count'})
        .sort_values(by='role_count', ascending=False)
        .head(100)
    )

In [44]:
df_count.head()

            id first_name last_name  role_count
22034    45332        Mel     Blanc         909
301306  621468       Bess   Flowers         672
173356  356804        Bud   Osborne         544
95634   196924     Oliver     Hardy         450
240782  495946     Emmett     Vogan         447